/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package img.recognition.ml;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
