spring:
  application.name: ml-img-recognition
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: ml-img-recognition

img.kafka.topic: img-topic
decision.kafka.topic: decision-topic

tf:
  frozenModelPath: inception-v3/inception_v3_2016_08_28_frozen.pb
  labelsPath: inception-v3/imagenet_slim_labels.txt
  outputLayer: InceptionV3/Predictions/Reshape_1
  image:
    width: 299
    height: 299
    mean: 0
    scale: 255